### ISSUE TITLE
Add Mechanoids Are Capable (Biotech DLC) patch

### ISSUE THREAD

**Issue by LionelColaso** [jefferyharrell/ManyJobs#73]
![image](https://github.com/CaptainArbitrary/ManyJobs/assets/2488703/6f7e61d8-e7dc-46e3-a1af-db97cd905f08)
Checkout the above patch from
[[FSF] Complex Jobs 1.4 Remaster](https://steamcommunity.com/sharedfiles/filedetails/?id=3019961011)
Should also fix issue 
[Add support patch for Tiered Mechs](https://github.com/CaptainArbitrary/ManyJobs/issues/70)

**Comment by jefferyharrell** [comment]
Okay, I'll check it out. Thanks!

**Comment by jefferyharrell** [comment]
I've looked at this, and I think it's beyond the scope of what I want Many Jobs to be. This seems like it should be its own mod.
